/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as temp from "./temp";
export type { temp };
import type * as tmp from "./tmp";
export type { tmp };
export * as factories from "./factories";
export type { Voting } from "./temp/hardhat/contracts/Voting";
export { Voting__factory } from "./factories/temp/hardhat/contracts/Voting__factory";
